### ISSUE TITLE
Allow to install this extension easily to Docker Lambda

### ISSUE THREAD

**Issue by tmokmss** [aws/aws-secretsmanager-agent#16]
In [README](https://github.com/aws/aws-secretsmanager-agent?tab=readme-ov-file#-aws-lambda-), there is only instructions for zip Lambda. It would be great if we could install this extension to Docker Lambda easily.

IMO [Lambda Web Adapter](https://github.com/awslabs/aws-lambda-web-adapter) has great usability on Docker Lambda. Their usage is like the following:

```dockerfile
# Dockerfile for Lambda function
FROM public.ecr.aws/docker/library/node:20-slim
# Just add this line to install the extension
COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:0.8.3 /lambda-adapter /opt/extensions/lambda-adapter
ENV PORT=7000
WORKDIR "/var/task"
ADD src/package.json /var/task/package.json
ADD src/package-lock.json /var/task/package-lock.json
RUN npm install --omit=dev
ADD src/ /var/task
CMD ["node", "index.js"]
```

[The existing extension ](https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_lambda.html) also requires some work to use it in Docker Lambda, so this can be a differentiator.

**Comment by simonmarty** [comment]
Captured in #17
