### ISSUE TITLE
Unable to run install script after cloning

### ISSUE THREAD

**Issue by rstevens011** [aws/aws-secretsmanager-agent#31]
**Describe the bug**
The install script doesn't work out of the box presenting a bad UX:

```
[root@ip-172-31-21-116 configuration]# pwd
/root/aws-secretsmanager-agent/aws_secretsmanager_agent/configuration
[root@ip-172-31-21-116 configuration]# ./install
Can not read aws_secretsmanager_agent
```

**To Reproduce**
1. Run through step 1 and proceed to step 2 in https://docs.aws.amazon.com/secretsmanager/latest/userguide/secrets-manager-agent.html.
2. Run the script via one of: `aws_secretsmanager_agent/configuration/install`  or `cd aws_secretsmanager_agent/configuration/ && ./install`

The script will fail:
```
[root@ip-172-31-21-116 aws-secretsmanager-agent]# aws_secretsmanager_agent/configuration/install
Can not read awssmaseedtoken
[root@ip-172-31-21-116 aws-secretsmanager-agent]# cd aws_secretsmanager_agent/configuration/ && ./install
Can not read aws_secretsmanager_agent
```
**Expected behavior**
The agent is installed and the systemd unit file is activated

**Environment**
AL2023

Platform, Rust Version, etc.
```
[root@ip-172-31-21-116 configuration]# cargo --version
cargo 1.81.0 (2dbb1af80 2024-08-20)
```
```
[root@ip-172-31-21-116 configuration]# rustc --version
rustc 1.81.0 (eeb90cda1 2024-09-04)
```
**Additional context**

**Comment by simonmarty** [comment]
Fixed in #34
